version: '2'
services:
 mag2:
  image: widyamedia/alpine36-php7.0
  volumes:
    - /data/docker/varwwwhtml:/usr/html
    - ./config/etc-nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./config/etc-nginx/server.conf:/etc/nginx/server.conf
    - ./config/etc-php7/php.ini:/etc/php7/php.ini
    - ./config/etc-php7/php-fpm.conf:/etc/php7/php-fpm.conf
    - ./config/etc-php7/php-fpm.d:/etc/php7/php-fpm.d
  ports:
    - "801:80"
  networks:
   - mag
  depends_on:
      - mysql

 mysql:
  image: widyamedia/alpine-mariadb
  volumes:
    - /data/docker/varlibmysql:/var/lib/mysql
    - ./config/etc-mysql/my.cnf:/etc/mysql/my.cnf
  networks:
    - mag

networks:
 mag:
  driver: bridge

